namespace DotsKit.Generation;

/// <summary>
/// What a version of the template can do, for a base generated by a version older than the tool. The tool takes
/// every minor of its major and the last minor of the one before (CONTRIBUTING.md, Releases), so each entry
/// names the major that removes its older branch.
/// </summary>
internal static class TemplateVersions
{
    /// <summary>
    /// <c>--Solution</c> since 2.8; before it the solution was <c>-M false</c>, which 3.0 removes. The <c>-M</c>
    /// branch goes in 3.0: its oldest base is the last 2.x, which has <c>--Solution</c>.
    /// </summary>
    private static readonly Version SolutionFlag = new(2, 8, 0);

    /// <summary>
    /// A service adds itself to All.sln by a post-action since 2.8; before it, by manual-add-projects.sh, which a
    /// command run by dotskit does not start. The tool's own adding (<see cref="Staging"/>) goes in 3.0.
    /// </summary>
    private static readonly Version SelfAddingService = new(2, 8, 0);

    public static bool HasSolutionFlag(string version) => IsAtLeast(version, SolutionFlag);

    public static bool AddsServiceToSolution(string version) => IsAtLeast(version, SelfAddingService);

    /// <summary>A version a manifest may name: a release, a pre-release (2.8.0-rc) or the template's sources.</summary>
    public static bool IsVersion(string version) =>
        version == TemplateSource.SourcesVersion || Version.TryParse(version.Split('-')[0], out _);

    /// <summary>The template's sources are always the newest; a pre-release (2.8.0-rc) is its release.</summary>
    private static bool IsAtLeast(string version, Version since) =>
        version == TemplateSource.SourcesVersion || Version.Parse(version.Split('-')[0]) >= since;
}
