namespace DotsKit;

/// <summary>Where things are in a solution generated by DotNetSolutionKit; the one place that knows the layout.</summary>
internal static class Layout
{
    public const string ProjectExtension = ".csproj";
    public const string ServicesFolder = "src/services";
    public const string CommonFolder = "src/common";
    public const string SolutionPattern = "*.All.sln";
    public const string SolutionSuffix = ".All.sln";
    public const string ManifestPath = ".dotskit/manifest.json";

    /// <summary>The solution folder All.sln keeps Common's projects in.</summary>
    public const string CommonSolutionFolder = "Common";

    /// <summary>What a generated tree holds that is not the template's: build output, git, the tool's own state.</summary>
    public static readonly string[] Ignored = ["bin", "obj", ".git", ".dotskit"];

    public static string ServicesOf(string root) => Path.Combine(root, ServicesFolder);

    public static string SolutionFileOf(string root) => Directory.GetFiles(ServicesOf(root), SolutionPattern).Single();
}

internal enum ExitCode
{
    Done = 0,
    Failed = 1,
    /// <summary>Written, with conflicts a person resolves before building.</summary>
    Conflicts = 2,
}
