namespace DotsKit.Solutions;

/// <summary>Where a solution generated by DotNetSolutionKit is: the folder with src/services/*.All.sln.</summary>
internal static class SolutionRoot
{
    /// <summary>The root of the solution <paramref name="start"/> is in, or null when it is in none.</summary>
    public static string? Find(string start)
    {
        for (var folder = new DirectoryInfo(start); folder is not null; folder = folder.Parent)
            if (HasSolution(folder.FullName))
                return folder.FullName;
        return null;
    }

    public static bool HasSolution(string folder)
    {
        if (!Directory.Exists(Layout.ServicesOf(folder)))
            return false;
        var solutions = Directory.GetFiles(Layout.ServicesOf(folder), Layout.SolutionPattern);
        return solutions.Length switch
        {
            0 => false,
            1 => true,
            _ => throw new InvalidOperationException($"{Layout.ServicesFolder} has {solutions.Length} {Layout.SolutionPattern} files: keep the solution's own one."),
        };
    }

    /// <summary>Nothing but what a fresh folder or repository holds: a new solution goes there, or beside files a clean git tree holds.</summary>
    public static bool IsEmpty(string folder) =>
        !Directory.Exists(folder) || Directory.EnumerateFileSystemEntries(folder).All(e => Path.GetFileName(e) == ".git");
}
