using System.Text.Json;
using System.Text.RegularExpressions;

namespace DotsKit.Reading;

/// <summary>
/// Reads the manifest of a solution made without dotskit from its files: the names from All.sln, the solution's
/// parameters from what Common and the root have, each service by its own files (<see cref="Markers"/>). Pure: it
/// decides from what <see cref="ISolutionFiles"/> gives, and refuses with a line that says what to do.
/// </summary>
internal static partial class SolutionReader
{
    private const string On = "true";
    private const string Off = "false";
    private const string ServicesFolder = Layout.ServicesFolder + "/";

    private static readonly JsonDocumentOptions JsonOptions = new() { CommentHandling = JsonCommentHandling.Skip, AllowTrailingCommas = true };

    /// <summary>The image name of build-images.sh: the product in lower case with underscores, then the service.</summary>
    [GeneratedRegex("""name="(?<product>[a-z0-9_]+)-\$\(""")]
    private static partial Regex ImageName();

    [GeneratedRegex("""localhost:(?<port>\d+)""")]
    private static partial Regex LocalPort();

    /// <summary>The version the template wrote into Directory.Build.props, or null when it wrote none (before 2.7).</summary>
    public static string? Version(ISolutionFiles files) => ElementOf(files.Read(Markers.BuildPropsPath), Markers.VersionElement);

    /// <summary>The prefix of the solution, NamespaceRoot.ProductName, from the name of its All.sln.</summary>
    public static string Prefix(string solutionFileName) => solutionFileName[..^Layout.SolutionSuffix.Length];

    /// <summary>The folders of src/services that are services of the template: each has its API project by its own name.</summary>
    public static IReadOnlyList<string> ServiceFolders(ISolutionFiles files, string prefix) =>
        [.. files.Folders(Layout.ServicesFolder)
            .Where(f => f.StartsWith(prefix + ".", StringComparison.Ordinal) && files.Exists(ServicePath(Markers.ApiProject, prefix, f)))];

    /// <summary>The name a service was generated with: its folder without the prefix.</summary>
    public static string ServiceName(string prefix, string folder) => folder[(prefix.Length + 1)..];

    /// <summary>The version a service says it was generated by, or null when it says none.</summary>
    public static string? ServiceVersion(ISolutionFiles files, string prefix, string folder) =>
        ElementOf(files.Read(ServicePath(Markers.ApiProject, prefix, folder)), Markers.ServiceVersionElement);

    /// <summary>
    /// The manifest of the solution: the solution's own parameters as its root and Common have them, then each
    /// service. The solution is not widened by its services, as dotskit new widens it: the template alone made the
    /// root with the first command and left it so, and the manifest is the base the files were generated from.
    /// The next dotskit new widens it, and brings what a service's flag needs outside its folder as new.
    /// </summary>
    /// <param name="given">What the command names itself: -N and -P where the name of All.sln does not tell them apart.</param>
    public static Manifest Read(ISolutionFiles files, string prefix, string version, TemplateArgs given)
    {
        var services = FirstServiceFirst(files, prefix, ServiceFolders(files, prefix));
        if (services.Count == 0)
            throw new InvalidOperationException($"{Layout.ServicesFolder} has no service of the template: dotskit new -S <Service> adds one.");
        var solution = Solution(files, prefix, Names(files, prefix, given), services[0]);
        var manifest = new Manifest { Template = version, Solution = solution.ToArgs(), Services = [] };
        return services.Aggregate(manifest, (m, folder) => m.WithServiceAsItIs(Service(files, prefix, folder)));
    }

    /// <summary>The service folders with the one the solution was made with first, where the solution tells it (<see cref="Markers.FirstServiceScript"/>).</summary>
    private static IReadOnlyList<string> FirstServiceFirst(ISolutionFiles files, string prefix, IReadOnlyList<string> services)
    {
        var script = (files.Read(Markers.FirstServiceScript) ?? "").ReplaceLineEndings("\n").Split('\n');
        var first = services.FirstOrDefault(f => script.Any(l => l.TrimEnd().EndsWith($"# {f}", StringComparison.Ordinal)));
        return first is null ? services : [first, .. services.Where(f => f != first)];
    }

    /// <summary>A service of the solution by its files, to add to a manifest that does not list it.</summary>
    public static TemplateArgs Service(ISolutionFiles files, string prefix, string folder)
    {
        var name = ServiceName(prefix, folder);
        var args = TemplateArgs.Empty.With(TemplateArgs.ServiceName, name);
        if (Port(files, prefix, folder) is { } port)
            args = args.With(TemplateArgs.HttpPort, port);
        if (files.Exists(ServicePath(Markers.GatewayFile, prefix, folder)))
            return args.With("ApiGateway", On);
        var settings = Sections(files.Read(ServicePath(Markers.AppSettings, prefix, folder)));
        if (!settings.Contains(Markers.HangfireSection))
            args = args.With("Hangfire", Off);
        if (Messaging(files, prefix, folder, settings) is { } messaging)
            args = args.With("Messaging", messaging);
        foreach (var (flag, section) in Markers.ServiceSections.Where(s => settings.Contains(s.Section)))
            args = args.With(flag, On);
        if (settings.Contains(Markers.EmailSection))
            args = args.With("Notify", "email");
        if (Contains(files, ServicePath(Markers.ProgramFile, prefix, folder), Markers.DiffApiLine))
            args = args.With("DiffApi", On);
        if (Contains(files, ServicePath(Markers.ConfigurationFile, prefix, folder), Markers.FeatureFlagsLine))
            args = args.With("FeatureFlags", On);
        if (files.Exists(ServicePath(Markers.AuditGuardFile, prefix, folder)))
            args = args.With("Audit", On);
        return args;
    }

    /// <summary>
    /// NamespaceRoot and ProductName. The name of All.sln joins them with a dot that a part may have too, so the
    /// split is read from the image names of build-images.sh, which write the product alone; two parts split
    /// themselves; otherwise the command names them.
    /// </summary>
    private static (string Root, string Product) Names(ISolutionFiles files, string prefix, TemplateArgs given)
    {
        if (given.Has("NamespaceRoot") && given.Has("ProductName"))
            return Checked(prefix, given["NamespaceRoot"]!, given["ProductName"]!);
        var parts = prefix.Split('.');
        if (ImageName().Match(files.Read(Markers.BuildImagesPath) ?? "") is { Success: true } image)
        {
            // The image writes the product in lower case with each dot as an underscore: the cut whose tail gives it.
            var product = image.Groups["product"].Value;
            for (var cut = 1; cut < parts.Length; cut++)
                if (string.Join('_', parts[cut..]).ToLowerInvariant() == product)
                    return Checked(prefix, string.Join('.', parts[..cut]), string.Join('.', parts[cut..]));
        }
        if (parts.Length == 2)
            return (parts[0], parts[1]);
        throw new ArgumentException($"{prefix} does not tell its NamespaceRoot from its ProductName: name them, dotskit init -N <NamespaceRoot> -P <ProductName>.");
    }

    private static (string Root, string Product) Checked(string prefix, string root, string product) =>
        string.Equals($"{root}.{product}", prefix, StringComparison.Ordinal)
            ? (root, product)
            : throw new ArgumentException($"-N {root} -P {product} make {root}.{product}, the solution is {prefix}: name its own parts.");

    /// <summary>The parameters of the whole solution, and the flags Common and the root were generated with.</summary>
    private static TemplateArgs Solution(ISolutionFiles files, string prefix, (string Root, string Product) names, string firstService)
    {
        var args = TemplateArgs.Empty.With("NamespaceRoot", names.Root).With("ProductName", names.Product);
        args = NotDefault(args, "Database", files.Exists(Markers.Of(Markers.SqlServerPath, prefix)) ? "mssql" : "postgres");
        args = NotDefault(args, "Deploy", files.Exists(Markers.ComposePath) ? "compose" : files.Exists(Markers.KubernetesPath) ? "k8s" : "none");
        args = NotDefault(args, "Agent", files.Exists(Markers.ClaudePath) ? "claude" : files.Exists(Markers.OpenCodePath) ? "opencode" : "none");
        args = NotDefault(args, "TestFramework", Contains(files, ServicePath(Markers.TestsProject, prefix, firstService), Markers.XunitLine) ? "xunit" : "nunit");
        foreach (var (flag, path) in Markers.SolutionFlags.Where(m => files.Exists(Markers.Of(m.Path, prefix))))
            args = args.With(flag, On);
        if (files.Exists(Markers.Of(Markers.NotifyEmailPath, prefix)))
            args = args.With("Notify", "email");
        if (files.Exists(Markers.Of(Markers.AuditPath, prefix)))
            args = args.With("Audit", On).With("Messaging", "outbox");
        return RootOnly(files, args);
    }

    /// <summary>
    /// Hangfire and the bus of the solution show only in .env.example of compose; elsewhere the services' own
    /// give them, as dotskit new widens the solution by each service.
    /// </summary>
    private static TemplateArgs RootOnly(ISolutionFiles files, TemplateArgs args)
    {
        if (files.Read(Markers.EnvExamplePath) is not { } env)
            return args.With("Hangfire", Off);
        args = NotDefault(args, "Hangfire", env.Contains(Markers.HangfireEnvLine, StringComparison.Ordinal) ? On : Off);
        return env.Contains(Markers.RabbitMqEnvLine, StringComparison.Ordinal) && !args.Has("Messaging") ? args.With("Messaging", "direct") : args;
    }

    /// <summary>The value, given only where it is not the template's default: a manifest names what was chosen, as dotskit new writes it.</summary>
    private static TemplateArgs NotDefault(TemplateArgs args, string name, string value) =>
        string.Equals(TemplateArgs.Empty[name], value, StringComparison.OrdinalIgnoreCase) ? args : args.With(name, value);

    private static string? Messaging(ISolutionFiles files, string prefix, string folder, IReadOnlySet<string> settings) =>
        !settings.Contains(Markers.BusSection) ? null
        : Contains(files, ServicePath(Markers.ConfigurationFile, prefix, folder), Markers.OutboxLine) ? "outbox"
        : "direct";

    private static string? Port(ISolutionFiles files, string prefix, string folder) =>
        LocalPort().Match(files.Read(ServicePath(Markers.LaunchSettings, prefix, folder)) ?? "") is { Success: true } m ? m.Groups["port"].Value : null;

    /// <summary>The top-level sections of appsettings.json; none when it is gone or no longer JSON.</summary>
    private static HashSet<string> Sections(string? json)
    {
        if (json is null)
            return [];
        try
        {
            using var document = JsonDocument.Parse(json.TrimStart('﻿'), JsonOptions);
            return document.RootElement.ValueKind == JsonValueKind.Object
                ? document.RootElement.EnumerateObject().Select(p => p.Name).ToHashSet(StringComparer.Ordinal)
                : [];
        }
        catch (JsonException)
        {
            return [];
        }
    }

    private static bool Contains(ISolutionFiles files, string path, string text) =>
        files.Read(path)?.Contains(text, StringComparison.Ordinal) == true;

    private static string ServicePath(string path, string prefix, string folder) => ServicesFolder + Markers.Of(path, prefix, folder);

    private static string? ElementOf(string? xml, string element)
    {
        if (xml is null)
            return null;
        var match = Regex.Match(xml, $"<{element}>([^<]+)</{element}>");
        return match.Success ? match.Groups[1].Value.Trim() : null;
    }
}
