#!/usr/bin/env bash
#
# Checks a generated solution for the template's authorship and version:
#
#   scripts/check-authorship.sh <solution> <version>   # <version>: 2.6.3, or "source" from the sources
#
# The files that carry the line "Part of DotNetSolutionKit ... Vladimir Savkin" carry it; a file a flag
# leaves out (marked "?") is checked when it is there. A glob names the twins of one mechanism, the
# PostgreSQL and the SQL Server one: a solution has one of them, and the one it has is checked.
# Directory.Build.props names the version. No file says <auto-generated>: Roslyn would treat it as
# generated code and switch its analyzers off.
set -euo pipefail

solution="$1" version="$2"
cd "$solution"

mark="Copyright (c) 2025 Vladimir Savkin"
common="src/common/*.Common"
files=(
    "Directory.Build.props"
    "Dockerfile"
    "$common.Application/Events/DomainEventDispatcher.cs"
    "$common.Application/Events/Readme.md"
    "$common.Infrastructure/Persistence/EntityFramework/Events/DomainEventTransactionInterceptor.cs"
    "$common.Infrastructure/Persistence/*/*SchemaGuard.cs"
    "$common.Web/Setup/PlatformWebHost.cs"
    "$common/Domain/Specifications/QuerySpecification.cs"
    "$common.Infrastructure/Persistence/EntityFramework/EntityFrameworkRepository.cs"
    "$common.Application/Idempotency/IdempotentExecutor.cs"
    "$common.Web/Authorization/PermissionAuthorizationFilter.cs"
    "$common.Web/Authentication/CsrfProtectionMiddleware.cs"
    "$common.Web/Tracing/CorrelationIdMiddleware.cs"
    "$common.Infrastructure/Http/Internal/InternalServiceHttpExtensions.cs"
    "$common.Infrastructure/Messaging/README.md"
    "$common.Testing/*DbTestExecutionContext.cs"
    "src/services/*/*.API/Controllers/README.md"
    "?$common.Web/Setup/SchemaDump.cs"
    "?$common.Web/Setup/SchemaOnlyMode.cs"
    "?$common.Infrastructure/Persistence/EntityFramework/Audit/AuditSaveChangesInterceptor.cs"
    "?$common.Infrastructure/Persistence/EntityFramework/Audit/SetBasedAuditCapture.cs"
    "?$common.Testing/Audit/AuditMarkerVerifier.cs"
    "?$common.Infrastructure/Configuration/Secrets/InfisicalSecretStore.cs"
    "?$common.Application/FeatureManagement/FileFeatureStore.cs"
    "?.github/workflows/ci.yml"
    "?.github/workflows/api-diff.yml"
    "?scripts/generate-api-schemas.sh"
    "?deploy/build-images.sh"
    "?deploy/compose/bluegreen.sh"
)

failed=0 checked=0
for pattern in "${files[@]}"; do
    optional=0
    [[ "$pattern" == \?* ]] && optional=1 pattern="${pattern#\?}"
    found=0
    for file in $pattern; do
        [ -f "$file" ] || continue
        found=1 checked=$((checked + 1))
        grep -qF "$mark" "$file" || { echo "::error::$file has no authorship line"; failed=1; }
    done
    if [ $found = 0 ] && [ $optional = 0 ]; then
        echo "::error::$pattern is not in the solution"
        failed=1
    fi
done

# The gateway's Program.cs: the one that uses Common.Web.Gateway.
for file in $(grep -lE '^using .*\.Common\.Web\.Gateway;' src/services/*/*.API/Program.cs 2>/dev/null || true); do
    checked=$((checked + 1))
    grep -qF "$mark" "$file" || { echo "::error::$file has no authorship line"; failed=1; }
done

stated=$(sed -n 's:.*<DotNetSolutionKitVersion>\(.*\)</DotNetSolutionKitVersion>.*:\1:p' Directory.Build.props)
if [ "$stated" != "$version" ]; then
    echo "::error::Directory.Build.props names DotNetSolutionKit $stated, expected $version"
    failed=1
fi

if grep -rlI --exclude-dir=.git --exclude-dir=bin --exclude-dir=obj '<auto-generated' .; then
    echo "::error::the files above say <auto-generated>, and Roslyn switches their analyzers off"
    failed=1
fi

echo "$checked files carry the authorship line; the solution names DotNetSolutionKit $stated"
exit $failed
