using DotsKit.Generation;
using DotsKit.Io;
using DotsKit.Reading;
using DotsKit.Solutions;

namespace DotsKit.Commands;

/// <summary>
/// <c>dotskit init</c>: describes a solution made without dotskit in its manifest. Reads the manifest from the
/// solution's files, generates the solution again by it with the version it names, shows how much of the
/// template's files that reproduces, and writes <c>.dotskit/manifest.json</c> - and nothing else - after a yes.
/// A solution with a manifest gets the services it does not list.
/// </summary>
/// <param name="onSources">The tool runs against the template's sources: a solution of version "source" is theirs.</param>
internal sealed class InitCommand(IStaging staging, ISolutionProjects projects, ITerminal terminal, string toolVersion, bool onSources)
{
    public async Task<ExitCode> RunAsync(Options options, string folder, CancellationToken ct)
    {
        var root = SolutionRoot.Find(folder) ?? throw new InvalidOperationException(SolutionRoot.IsEmpty(folder)
            ? "No solution here: dotskit new -N <Company> -P <Product> -S <Service> makes one, with its manifest."
            : $"Not a solution of DotNetSolutionKit: there is no {Layout.ServicesFolder}/{Layout.SolutionPattern}.");
        var files = new DiskSolutionFiles(root);
        var prefix = SolutionReader.Prefix(Path.GetFileName(Layout.SolutionFileOf(root)));
        var given = Given(options);
        var current = Manifest.Load(root);
        var next = current is null ? Described(files, prefix, options, given) : WithUnlisted(current, files, prefix, options);
        if (next is null)
            return Current(current!);
        if (!files.Exists(Layout.CommonFolder))
            return await WriteAsync(root, next, options,
                "No Common: the solution's database and flags, which are read from it, are the template's defaults here, and there is nothing to check the reading against. dotskit new takes Common for removed by the team and does not add it back.");
        var reproduction = await CheckAsync(root, next, ct);
        foreach (var line in reproduction.Lines())
            terminal.Info(line);
        return await WriteAsync(root, next, options, reproduction.IsWhole ? null : "A file that differs is a change of yours or a wrong reading: check them before you rely on the manifest.");
    }

    /// <summary>The names -N and -P, the only arguments of the template init takes: everything else it reads.</summary>
    private static TemplateArgs Given(Options options)
    {
        var given = TemplateArgs.Parse(options.TemplateArgs);
        var other = given.Without("NamespaceRoot", "ProductName").ToArgs();
        return other.Count == 0
            ? given
            : throw new ArgumentException($"dotskit init reads the solution's parameters from its files and takes only -N and -P; leave out {string.Join(' ', other)}.");
    }

    /// <summary>The manifest of a solution without one, of the version it says or the command names.</summary>
    private Manifest Described(ISolutionFiles files, string prefix, Options options, TemplateArgs given)
    {
        var version = options.TemplateVersion ?? SolutionReader.Version(files);
        if (TemplateVersions.WhyNotDescribed(version, toolVersion, onSources) is { } why)
            throw new InvalidOperationException(why);
        RefuseServicesOfOtherVersions(files, prefix, SolutionReader.ServiceFolders(files, prefix), version!, options);
        return SolutionReader.Read(files, prefix, version!, given);
    }

    /// <summary>
    /// A service generated by another version than the manifest's: the manifest keeps one version, and the check
    /// generates the service by it. A person names the version to describe the solution by, and the check shows
    /// what differs.
    /// </summary>
    private static void RefuseServicesOfOtherVersions(ISolutionFiles files, string prefix, IEnumerable<string> services, string version, Options options)
    {
        if (options.TemplateVersion is not null)
            return;
        var others = services
            .Select(f => (Name: SolutionReader.ServiceName(prefix, f), Version: SolutionReader.ServiceVersion(files, prefix, f)))
            .Where(s => s.Version is not null && s.Version != version && s.Version != TemplateSource.SourcesVersion)
            .ToList();
        if (others.Count > 0)
            throw new InvalidOperationException(
                $"The solution is {version}, and {string.Join(", ", others.Select(s => $"{s.Name} is {s.Version}"))}: the manifest keeps one version; "
                + $"name the one to describe the solution by, dotskit init --template-version {version}, and the check shows what differs.");
    }

    /// <summary>The manifest with the services of src/services it does not list; null when it lists them all.</summary>
    private static Manifest? WithUnlisted(Manifest current, ISolutionFiles files, string prefix, Options options)
    {
        var unlisted = SolutionReader.ServiceFolders(files, prefix)
            .Where(f => current.FindService(SolutionReader.ServiceName(prefix, f)) is null)
            .ToList();
        if (options.TemplateVersion is { } named && named != current.Template)
            throw new ArgumentException($"The manifest is {current.Template}: a service it does not list is described by that version, not {named}; dotskit upgrade moves the manifest to another.");
        RefuseServicesOfOtherVersions(files, prefix, unlisted, current.Template, options);
        return unlisted.Count == 0 ? null : unlisted.Aggregate(current, (m, f) => m.WithServiceAsItIs(SolutionReader.Service(files, prefix, f)));
    }

    private ExitCode Current(Manifest manifest)
    {
        terminal.Info($"The manifest is current: {manifest.Template}, services {string.Join(", ", manifest.ServiceArgs.Select(s => s.Service))}.");
        return ExitCode.Done;
    }

    /// <summary>The solution generated again by the manifest, compared with the folder.</summary>
    private async Task<Reproduction> CheckAsync(string root, Manifest manifest, CancellationToken ct)
    {
        terminal.Info($"Generating the solution again by the template {manifest.Template} to check the reading...");
        var staged = await staging.BuildAsync(manifest, ct);
        return Reproduction.Of(root, staged,
            await projects.ListAsync(Layout.SolutionFileOf(root), ct),
            await projects.ListAsync(Layout.SolutionFileOf(staged), ct));
    }

    private async Task<ExitCode> WriteAsync(string root, Manifest manifest, Options options, string? note)
    {
        terminal.Info($"  manifest  {Layout.ManifestPath}");
        terminal.Info(manifest.Serialize().TrimEnd());
        if (note is not null)
            terminal.Info(note);
        if (!options.Yes && !terminal.Confirm("Write the manifest?"))
        {
            terminal.Info("Nothing written: answer y to write, or pass --yes where no one can answer.");
            return ExitCode.Failed;
        }
        var transaction = new FileTransaction(root);
        transaction.Write(Layout.ManifestPath, System.Text.Encoding.UTF8.GetBytes(manifest.Serialize()));
        await transaction.CommitAsync(() => Task.CompletedTask);
        terminal.Info($"Written {Layout.ManifestPath}: dotskit new and dotskit upgrade work from it.");
        return ExitCode.Done;
    }
}
