using DotsKit.Generation;
using DotsKit.Io;
using DotsKit.Planning;
using DotsKit.Solutions;

namespace DotsKit.Commands;

/// <summary>
/// <c>dotskit upgrade</c>: brings a solution to the tool's version of the template, keeping what the team changed.
/// The same three-way merge as dotskit new, with the solution's manifest generated by its own version as the base
/// and by the tool's as the target; the files the template moved take the team's changes with them, and the
/// package versions follow the manifest's policy.
/// </summary>
/// <param name="onSources">The tool runs against the template's sources: it upgrades any release to them.</param>
internal sealed class UpgradeCommand(IPlanner planner, PlanExecution execution, IGit git, ITerminal terminal, string toolVersion, bool onSources)
{
    public async Task<ExitCode> RunAsync(Options options, string folder, CancellationToken ct)
    {
        if (options.TemplateArgs.Count > 0)
            throw new ArgumentException($"dotskit upgrade takes no parameter of the template; leave out {string.Join(' ', options.TemplateArgs)}: dotskit new adds a service or a flag.");
        var root = SolutionRoot.Find(folder)
            ?? throw new InvalidOperationException($"No solution here: dotskit upgrade runs in a solution, a folder with {Layout.ServicesFolder}/{Layout.SolutionPattern} or below it.");
        var current = Manifest.Load(root)
            ?? throw new InvalidOperationException($"{Layout.ManifestPath} is missing: describe the solution first, dotskit init.");
        var target = onSources ? TemplateSource.SourcesVersion : toolVersion;
        if (current.Template == target)
        {
            terminal.Info($"The solution is of the template {target} already.");
            return ExitCode.Done;
        }
        if (TemplateVersions.WhyNotUpgraded(current.Template, toolVersion, onSources) is { } why)
            throw new InvalidOperationException(why);
        if (!options.AllowDirty && !await git.IsCleanAsync(root, ct))
            throw new InvalidOperationException("The git working tree has uncommitted changes: commit or stash them, so what dotskit writes can be seen and undone (--allow-dirty to go on).");
        terminal.Info($"Upgrading the solution from the template {current.Template} to {target}.");
        var plan = await planner.BuildAsync(root, current, current.WithTemplate(target), options.Force, ct);
        return await execution.RunAsync(plan, options, ct);
    }
}
